[2024-10-16T00:00:00.875+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T00:00:00.882+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.print_hello_world scheduled__2024-10-15T23:57:00+00:00 [queued]>
[2024-10-16T00:00:00.885+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.print_hello_world scheduled__2024-10-15T23:57:00+00:00 [queued]>
[2024-10-16T00:00:00.885+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-16T00:00:00.891+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): print_hello_world> on 2024-10-15 23:57:00+00:00
[2024-10-16T00:00:00.894+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28186) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-16T00:00:00.895+0000] {standard_task_runner.py:72} INFO - Started process 28187 to run task
[2024-10-16T00:00:00.895+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'print_hello_world', 'scheduled__2024-10-15T23:57:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/chinedu_message.py', '--cfg-path', '/tmp/tmpwfjtfku_']
[2024-10-16T00:00:00.896+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask print_hello_world
[2024-10-16T00:00:00.922+0000] {task_command.py:467} INFO - Running <TaskInstance: simple_dag.print_hello_world scheduled__2024-10-15T23:57:00+00:00 [running]> on host 7e94db92b8fb
[2024-10-16T00:00:00.951+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='print_hello_world' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:57:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-15T23:57:00+00:00'
[2024-10-16T00:00:00.952+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-16T00:00:00.952+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-16T00:00:00.952+0000] {logging_mixin.py:190} INFO - Current task name:print_hello_world state:running start_date:2024-10-16 00:00:00.882435+00:00
[2024-10-16T00:00:00.953+0000] {logging_mixin.py:190} INFO - Dag name:simple_dag and current dag run status:running
[2024-10-16T00:00:00.953+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T00:00:00.953+0000] {logging_mixin.py:190} INFO - Hello, Airflow!
[2024-10-16T00:00:00.953+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-16T00:00:00.957+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T00:00:00.957+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=print_hello_world, run_id=scheduled__2024-10-15T23:57:00+00:00, execution_date=20241015T235700, start_date=20241016T000000, end_date=20241016T000000
[2024-10-16T00:00:00.957+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: configure_rocketchat_success_alert
[2024-10-16T00:00:00.957+0000] {taskinstance.py:1567} ERROR - Error in callback at index 0: configure_rocketchat_success_alert
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1565, in _run_finished_callback
    callback(context)
TypeError: configure_rocketchat_success_alert() takes 0 positional arguments but 1 was given
[2024-10-16T00:00:00.960+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-16T00:00:00.961+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-16T00:00:00.961+0000] {logging_mixin.py:190} INFO - Dag name:simple_dag queued_at:2024-10-16 00:00:00.649868+00:00
[2024-10-16T00:00:00.961+0000] {logging_mixin.py:190} INFO - Task hostname:7e94db92b8fb operator:PythonOperator
[2024-10-16T00:00:00.995+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-16T00:00:01.003+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T00:00:01.004+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
